//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempusVelit.Database
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class ControlTask
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlTask()
        {
            this.Questions = new ObservableCollection<Question>();
            this.UserControlTasks = new ObservableCollection<UserControlTask>();
        }
    
        public int TaskID { get; set; }
        public string ImageSource { get; set; }
        public int LessonID { get; set; }
        public string RequiredTables { get; set; }
        public string RequiredConditions { get; set; }
        public string RequiredColumns { get; set; }
    
        public virtual Lesson Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<UserControlTask> UserControlTasks { get; set; }
    }
}
