//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempusVelit.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TempusVelitEntities : DbContext
    {
        public TempusVelitEntities()
            : base("name=TempusVelitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<ControlTask> ControlTask { get; set; }
        public virtual DbSet<LearningModule> LearningModule { get; set; }
        public virtual DbSet<Lesson> Lesson { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Stage> Stage { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserControlTask> UserControlTask { get; set; }
        public virtual DbSet<UserLesson> UserLesson { get; set; }
    }
}
