//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempusVelit.Database
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class UserAchievement
    {
        public int UserAchievementID { get; set; }
        public int UserID { get; set; }
        public int AchievementID { get; set; }
    
        public virtual Achievement Achievement { get; set; }
        public virtual User User { get; set; }
    }
}
