//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempusVelit.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserControlTask
    {
        public int UserControlTaskID { get; set; }
        public int UserID { get; set; }
        public int TaskID { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual ControlTask ControlTask { get; set; }
        public virtual User User { get; set; }
    }
}
